my_list=[]
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
print(f"List after appending: {my_list}")
my_list.insert(1,15)
print(f"List after inserting 15 at position 2: {my_list}")
my_list.pop()
print("list after removing the last element: {my_list}")
my_list.sort()
print("list after sorting: {my_list}")
index_of_30 = my_list.index(30)
print(index_of_30)